#!/usr/bin/env python3
"""Coordinate-MH inverse-blocking diagnostic for factor-two lattices.

The wrapped flow is used only to construct sweep-zero details.  Subsequent
transitions are direct random walks in physical inverse-blocking coordinates
`(c, d01, d10, d11)`.  Coarse proposals are first generated by the same
per-site Metropolis kernel targeting `exp(-S_c)` used by the four-substep
test; detail proposals are symmetric Gaussian random walks.  The fixed linear
map to the fine field has a state-independent Jacobian and cancels.
"""
from __future__ import annotations

import argparse
import csv
import json
import os
import sys
import time
import traceback
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import torch

PROJECT_ROOT = Path(__file__).resolve().parents[2]
PKG = PROJECT_ROOT / "perfect_blocking_upsampling"
sys.path[:0] = [str(PKG / "src"), str(PKG / "scripts")]

from perfect_blocking_upsampling.actions import ActionSpec, action_total  # noqa: E402
from perfect_blocking_upsampling.blocking import apply_kernel, assemble_psi, inverse_kernel, load_kernel_matrix, load_phi  # noqa: E402
from perfect_blocking_upsampling.improved_tail_map import apply as apply_improved_tail_map, parameters as improved_tail_map_parameters  # noqa: E402
from perfect_blocking_upsampling.wrapped_flow_coordinates import detail_from_psi  # noqa: E402
from run_lam1p0_l16to32_rqspline_zeroshot import (  # noqa: E402
    build_model_from_checkpoint,
    per_config_observables,
    sample_model_lattice,
    stationary_stats,
)
from run_lam1p0_mit_style_inverse_blocking_L8to16 import (  # noqa: E402
    ACCEPT_COLUMNS,
    DEFAULT_CHECKPOINT,
    DEFAULT_KERNEL,
    G_COLUMNS,
    MAIN_COLUMNS,
    aggregate,
    append_csv,
    reblock_error,
    write_csv,
    write_json,
)

DEFAULT_COARSE = PROJECT_ROOT / "data/configs_phi4_2d/lam1p0_kappac0p340301_L8/configs.npz"
DEFAULT_NATIVE = PROJECT_ROOT / "data/configs_phi4_2d/lam1p0_kappac0p340301_L16/configs.npz"
DEFAULT_OUT = PKG / "outputs/controlled_patch_lam1p0/mit_coordinate_mh_L8to16"
REB_TOL = 5.0e-6

COORD_COLUMNS = [
    "sweep", "detail_pass", "chain_id", "coordinate", "subset_y", "subset_x", "active_sites",
    "attempted", "accepted", "old_S_f", "new_S_f", "delta_S_f", "log_accept_ratio",
    "old_S_c", "new_S_c", "coarse_kernel_site_accepts", "log_uniform", "reblocking_max_error",
]
SUBSTEP_COLUMNS = [
    "sweep", "detail_pass", "coordinate", "subset_y", "subset_x", "attempts", "accepts", "acceptance",
    "attempts_cumulative", "accepts_cumulative", "acceptance_cumulative",
]


@dataclass
class CoordinateState:
    phi: np.ndarray
    psi: np.ndarray
    coarse: np.ndarray
    detail: np.ndarray
    action: np.ndarray
    source_index: np.ndarray
    source_native_index: np.ndarray


def build_state(
    coarse: np.ndarray,
    detail: np.ndarray,
    source_index: np.ndarray,
    source_native_index: np.ndarray,
    *,
    kernel: np.ndarray,
    action: ActionSpec,
) -> CoordinateState:
    psi = assemble_psi(np.asarray(coarse, dtype=np.float32), np.asarray(detail, dtype=np.float32))
    phi, _ = inverse_kernel(psi, kernel)
    fine_action = action_total(phi, action).astype(np.float64)
    return CoordinateState(
        phi=np.asarray(phi, dtype=np.float32),
        psi=np.asarray(psi, dtype=np.float32),
        coarse=np.asarray(coarse, dtype=np.float32),
        detail=np.asarray(detail, dtype=np.float32),
        action=fine_action,
        source_index=np.asarray(source_index, dtype=np.int64).copy(),
        source_native_index=np.asarray(source_native_index, dtype=np.int64).copy(),
    )


def choose_state(old: CoordinateState, new: CoordinateState, accepted: np.ndarray) -> CoordinateState:
    def choose(a: np.ndarray, b: np.ndarray) -> np.ndarray:
        return np.where(accepted.reshape((-1,) + (1,) * (a.ndim - 1)), b, a)

    return CoordinateState(
        phi=choose(old.phi, new.phi),
        psi=choose(old.psi, new.psi),
        coarse=choose(old.coarse, new.coarse),
        detail=choose(old.detail, new.detail),
        action=choose(old.action, new.action),
        source_index=old.source_index.copy(),
        source_native_index=old.source_native_index.copy(),
    )


def measurement_rows(state: CoordinateState, sweep: int) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    obs, g = per_config_observables(state.phi, ActionSpec("phi4_nn", 1.0, 0.340301))
    lf = int(state.phi.shape[1])
    main: list[dict[str, Any]] = []
    grow: list[dict[str, Any]] = []
    for chain in range(len(state.phi)):
        main.append({
            "chain_id": chain, "sweep": sweep,
            "source_config_index": int(state.source_index[chain]),
            "source_native_L32_index": int(state.source_native_index[chain]),
            "L": lf, "volume": lf * lf,
            "action_density": float(obs["action_density"][chain]),
            "total_action": float(obs["total_action"][chain]),
            "phi2": float(obs["phi2"][chain]), "phi4": float(obs["phi4"][chain]),
            "NN": float(obs["NN"][chain]), "diag": float(obs["diag"][chain]),
            "2nn": float(obs["2nn"][chain]), "m": float(obs["m"][chain]),
            "m2": float(obs["m2"][chain]), "m4": float(obs["m4"][chain]),
            "G_pmin_x_cfg": float(g["G_10"][chain]),
            "G_pmin_y_cfg": float(g["G_01"][chain]),
            "nonfinite_count": int(np.sum(~np.isfinite(state.phi[chain]))),
        })
        grow.append({
            "chain_id": chain, "sweep": sweep,
            "source_config_index": int(state.source_index[chain]),
            "source_native_L32_index": int(state.source_native_index[chain]),
            "L": lf, "volume": lf * lf,
            "G_00": float(g["G_00"][chain]), "G_10": float(g["G_10"][chain]),
            "G_01": float(g["G_01"][chain]), "G_pmin_avg": float(g["G_pmin_avg"][chain]),
        })
    return main, grow


def save_checkpoint(path: Path, state: CoordinateState) -> None:
    tmp = path.with_suffix(".tmp.npz")
    np.savez_compressed(
        tmp, phi=state.phi, psi=state.psi, coarse=state.coarse, detail=state.detail,
        action=state.action, logq=np.full(len(state.action), np.nan),
        source_config_index=state.source_index, source_native_index=state.source_native_index,
    )
    os.replace(tmp, path)


def detail_map_jacobian_check(kernel: np.ndarray, lc: int) -> dict[str, float | bool | int]:
    """Numerically verify the fixed detail-to-fine linear volume element at L8."""
    if lc > 8:
        return {"performed": False, "reason": "restricted_to_Lc_at_most_8"}
    n_detail = 3 * lc * lc
    n_fine = 4 * lc * lc
    matrix = np.empty((n_fine, n_detail), dtype=np.float64)
    zero_c = np.zeros((1, lc, lc), dtype=np.float32)
    for index in range(n_detail):
        basis = np.zeros((1, 3, lc, lc), dtype=np.float32)
        sector, rem = divmod(index, lc * lc)
        y, x = divmod(rem, lc)
        basis[0, sector, y, x] = 1.0
        phi, _ = inverse_kernel(assemble_psi(zero_c, basis), kernel)
        matrix[:, index] = phi.reshape(-1)
    singular_values = np.linalg.svd(matrix, compute_uv=False)
    rng = np.random.default_rng(7321)
    d0 = rng.standard_normal((1, 3, lc, lc)).astype(np.float32)
    delta = rng.standard_normal((1, 3, lc, lc)).astype(np.float32)
    phi0, _ = inverse_kernel(assemble_psi(zero_c, d0), kernel)
    phi1, _ = inverse_kernel(assemble_psi(zero_c, d0 + delta), kernel)
    phi_delta, _ = inverse_kernel(assemble_psi(zero_c, delta), kernel)
    return {
        "performed": True,
        "detail_dimension": n_detail,
        "fine_dimension": n_fine,
        "min_singular_value": float(singular_values.min()),
        "max_singular_value": float(singular_values.max()),
        "detail_to_fine_log_volume": float(np.log(singular_values).sum()),
        "linearity_max_abs_error": float(np.max(np.abs((phi1 - phi0) - phi_delta))),
        "state_independent": True,
    }


def coarse_kernel_transition(
    coarse: np.ndarray,
    active_sites: np.ndarray,
    *,
    action: ActionSpec,
    sigma: float,
    n_steps: int,
    rng: np.random.Generator,
) -> tuple[np.ndarray, np.ndarray]:
    """Reversible per-site MH kernel whose invariant density is exp(-S_c)."""
    current = np.asarray(coarse, dtype=np.float32).copy()
    accepted = np.zeros(len(current), dtype=np.int64)
    active_flat = np.flatnonzero(active_sites.reshape(-1))
    if len(active_flat) == 0:
        raise RuntimeError("coarse subset contains no active sites")
    lam = float(action.lambda_)
    kappa = float(action.kappa)
    quadratic = 1.0 - 2.0 * lam
    lc = current.shape[1]
    for _ in range(n_steps):
        for flat in rng.permutation(active_flat):
            y, x = divmod(int(flat), lc)
            old = current[:, y, x].astype(np.float64)
            proposal = old + sigma * rng.standard_normal(len(current))
            neighbors = (
                current[:, (y - 1) % lc, x] + current[:, (y + 1) % lc, x]
                + current[:, y, (x - 1) % lc] + current[:, y, (x + 1) % lc]
            ).astype(np.float64)
            delta = quadratic * (proposal * proposal - old * old)
            delta += lam * (proposal**4 - old**4)
            delta -= 2.0 * kappa * (proposal - old) * neighbors
            take = np.log(rng.random(len(current))) < np.minimum(0.0, -delta)
            current[take, y, x] = proposal[take].astype(np.float32)
            accepted += take.astype(np.int64)
    return current, accepted


def write_measurements(run: Path, main: list[dict[str, Any]], g_rows: list[dict[str, Any]]) -> None:
    write_csv(run / "observables" / "main_per_sweep_measurements.csv", main, MAIN_COLUMNS)
    write_csv(run / "observables" / "per_sweep_observables.csv", main, MAIN_COLUMNS)
    write_csv(run / "observables" / "Gk_per_sweep_measurements.csv", g_rows, G_COLUMNS)
    write_csv(run / "observables" / "ensemble_average_history.csv", aggregate(main))


def main() -> int:
    ap = argparse.ArgumentParser(description="Exact target-action coordinate MH after wrapped-flow initialization.")
    ap.add_argument("--run-dir", type=Path, required=True)
    ap.add_argument("--coarse-proposal-source", type=Path, default=DEFAULT_COARSE)
    ap.add_argument("--native-reference-source", type=Path, default=DEFAULT_NATIVE)
    ap.add_argument("--flow-checkpoint", type=Path, default=DEFAULT_CHECKPOINT)
    ap.add_argument("--kernel-path", type=Path, default=DEFAULT_KERNEL)
    ap.add_argument("--from-L", type=int, default=8)
    ap.add_argument("--to-L", type=int, default=16)
    ap.add_argument("--n-chains", type=int, default=128)
    ap.add_argument(
        "--details-per-coarse", type=int, default=1,
        help="Independent wrapped-flow detail initializations per selected coarse configuration. "
        "n-chains is the total chain count and must be divisible by this value.",
    )
    ap.add_argument("--n-sweeps", type=int, default=400)
    ap.add_argument("--save-sweeps", default="0,1,2,5,10,20,50,100,200,400")
    ap.add_argument("--batch-size", type=int, default=32)
    ap.add_argument("--seed", type=int, default=2026072401)
    ap.add_argument("--device", default="cpu")
    ap.add_argument("--initial-start-index", type=int, default=0)
    ap.add_argument("--initialization", choices=("blocked_native", "blocked_native_flow", "direct_coarse_flow", "direct_coarse_impflow"), default="direct_coarse_flow")
    ap.add_argument("--improved-flow-map", choices=("none", "auto"), default="none", help="Use the frozen improved tail map with direct_coarse_impflow.")
    ap.add_argument("--improved-base-scale", type=float, default=None)
    ap.add_argument("--improved-tail-strength", type=float, default=None)
    ap.add_argument("--improved-tail-width", type=float, default=2.0)
    ap.add_argument("--resume-checkpoint", type=Path, default=None, help="Start a new coordinate-MH stage from a saved coordinate checkpoint. New run sweeps begin at zero.")
    ap.add_argument("--sweep-offset", type=int, default=0, help="Absolute sweep number represented by the resumed initial state.")
    ap.add_argument("--update-mode", choices=("detail_only", "coarse_detail"), default="detail_only")
    ap.add_argument("--coarse-sigma", type=float, default=0.04)
    ap.add_argument("--coarse-updates-per-sweep", type=int, default=1)
    ap.add_argument(
        "--coarse-proposal-mode", choices=("sc_reversible", "symmetric_rw"), default="sc_reversible",
        help="sc_reversible: S_c site-MH proposal with outer fine correction; symmetric_rw: Gaussian checkerboard coarse proposal with direct S_f acceptance.",
    )
    ap.add_argument("--detail-sigma", type=float, default=0.04)
    ap.add_argument(
        "--detail-passes-per-sweep", type=int, default=1,
        help="Complete detail-coordinate passes after the full coarse sweep. Each pass updates d01, d10, and d11 over every subset.",
    )
    ap.add_argument(
        "--initial-detail-only-sweeps", type=int, default=0,
        help="Optional exact detail-only MH sweeps after flow initialization and before numbered sweeps. Coarse fields remain fixed.",
    )
    ap.add_argument("--divide", type=int, choices=(1, 2), default=1)
    ap.add_argument("--smoke", action="store_true")
    args = ap.parse_args()
    if args.to_L != 2 * args.from_L or args.from_L not in {8, 16, 32}:
        raise RuntimeError("coordinate-MH diagnostic supports factor-two L8->L16, L16->L32, or L32->L64 only")
    if args.coarse_sigma <= 0.0 or args.detail_sigma <= 0.0 or args.coarse_updates_per_sweep <= 0 or args.detail_passes_per_sweep <= 0 or args.initial_detail_only_sweeps < 0 or args.sweep_offset < 0:
        raise RuntimeError("coarse/detail sigmas, coarse updates, and detail passes per sweep must be positive")
    if args.details_per_coarse <= 0 or args.n_chains % args.details_per_coarse:
        raise RuntimeError("n-chains must be divisible by a positive --details-per-coarse")
    if args.from_L % args.divide:
        raise RuntimeError("coarse lattice size must be divisible by --divide")
    if args.smoke:
        args.n_chains, args.n_sweeps, args.save_sweeps = min(args.n_chains, 4), min(args.n_sweeps, 3), "0,1,2,3"
    saves = {int(value) for value in args.save_sweeps.split(",") if value.strip()}
    saves.add(args.sweep_offset)

    run = args.run_dir.resolve()
    for name in ("logs", "observables", "plots", "summaries", "debug", "checkpoints"):
        (run / name).mkdir(parents=True, exist_ok=True)
    for path in (args.coarse_proposal_source, args.native_reference_source, args.flow_checkpoint, args.kernel_path):
        if not path.exists():
            raise RuntimeError(f"missing required path: {path}")
    kernel, kernel_meta = load_kernel_matrix(args.kernel_path)
    if not bool(kernel_meta.get("kernel_coefficients_include_eta_scale", False)):
        raise RuntimeError("kernel coefficients must already include eta scale")
    coarse_all = load_phi(args.coarse_proposal_source)
    native_all = load_phi(args.native_reference_source)
    lc, lf = args.from_L, args.to_L
    if coarse_all.shape[1:] != (lc, lc) or native_all.shape[1:] != (lf, lf):
        raise RuntimeError(f"source lattice shapes must be L{lc} and L{lf}")
    n_unique_coarse = args.n_chains // args.details_per_coarse
    if args.initial_start_index + n_unique_coarse > len(native_all):
        raise RuntimeError("not enough native reference configurations")
    if args.resume_checkpoint is None and args.initialization in {"direct_coarse_flow", "direct_coarse_impflow"} and args.initial_start_index + n_unique_coarse > len(coarse_all):
        raise RuntimeError("not enough direct coarse configurations")
    if args.resume_checkpoint is None and args.initialization == "direct_coarse_impflow" and args.improved_flow_map != "auto":
        raise RuntimeError("direct_coarse_impflow requires --improved-flow-map auto")
    if args.resume_checkpoint is not None and args.initial_detail_only_sweeps:
        raise RuntimeError("initial detail-only sweeps are only valid after flow initialization, not when resuming a checkpoint")

    device = torch.device(args.device)
    checkpoint = torch.load(args.flow_checkpoint, map_location=device, weights_only=False)
    model, load_report = build_model_from_checkpoint(checkpoint, lc, device)
    stats = stationary_stats(checkpoint["state"]["stats"], lc)
    action = ActionSpec("phi4_nn", 1.0, 0.340301)
    rng = np.random.default_rng(args.seed)
    source_index_unique = np.arange(args.initial_start_index, args.initial_start_index + n_unique_coarse, dtype=np.int64)
    source_index = np.repeat(source_index_unique, args.details_per_coarse)
    detail_replica_index = np.tile(np.arange(args.details_per_coarse, dtype=np.int64), n_unique_coarse)
    native_index = source_index.copy()
    native = native_all[source_index_unique].astype(np.float32)
    native_psi = apply_kernel(native, kernel)
    native_c = np.repeat(native_psi[:, 0::2, 0::2], args.details_per_coarse, axis=0).astype(np.float32)
    native_d = np.repeat(detail_from_psi(native_psi), args.details_per_coarse, axis=0).astype(np.float32)
    resume_info: dict[str, Any] | None = None
    improved_initializer: dict[str, Any] | None = None
    if args.resume_checkpoint is not None:
        if not args.resume_checkpoint.exists():
            raise RuntimeError(f"missing resume checkpoint: {args.resume_checkpoint}")
        payload = np.load(args.resume_checkpoint, allow_pickle=False)
        required_keys = {"phi", "coarse", "detail", "source_config_index", "source_native_index"}
        missing = required_keys.difference(payload.files)
        if missing:
            raise RuntimeError(f"resume checkpoint missing keys: {sorted(missing)}")
        if payload["coarse"].shape != (args.n_chains, lc, lc) or payload["detail"].shape != (args.n_chains, 3, lc, lc):
            raise RuntimeError("resume checkpoint shape does not match requested chain count/lattice")
        current = build_state(
            payload["coarse"], payload["detail"], payload["source_config_index"], payload["source_native_index"],
            kernel=kernel, action=action,
        )
        resume_phi_error = float(np.max(np.abs(current.phi.astype(np.float64) - payload["phi"].astype(np.float64))))
        if resume_phi_error > REB_TOL:
            raise RuntimeError(f"resume checkpoint reconstruction mismatch: {resume_phi_error:.6g}")
        initial_role = "resumed_coordinate_state"
        resume_info = {"checkpoint": str(args.resume_checkpoint.resolve()), "phi_reconstruction_max_abs_error": resume_phi_error}
    elif args.initialization == "blocked_native":
        current = build_state(native_c, native_d, np.full(args.n_chains, -1, dtype=np.int64), native_index, kernel=kernel, action=action)
        initial_role = "blocked_native_initial"
    elif args.initialization == "blocked_native_flow":
        # Stationarity complement: retain the exact coarse field K phi_native on
        # even-even sites, discard its native details, then draw d~q_theta(d|c).
        # This tests the conditional flow without the direct-Lc marginal error.
        detail, _logq, _zmax, _logdet = sample_model_lattice(
            model, native_c, stats, batch_size=args.batch_size, device=device,
            seed=int(rng.integers(2**31 - 1)),
        )
        current = build_state(native_c, detail, np.full(args.n_chains, -1, dtype=np.int64), native_index, kernel=kernel, action=action)
        initial_role = "blocked_native_coarse_wrapped_flow_detail_initial"
    else:
        coarse = np.repeat(coarse_all[source_index_unique], args.details_per_coarse, axis=0).astype(np.float32)
        detail, _logq, _zmax, _logdet = sample_model_lattice(
            model, coarse, stats, batch_size=args.batch_size, device=device,
            seed=int(rng.integers(2**31 - 1)),
        )
        if args.initialization == "direct_coarse_impflow":
            base_scale, tail_strength, tail_width = improved_tail_map_parameters(
                lc, base_scale=args.improved_base_scale, tail_strength=args.improved_tail_strength,
                tail_width=args.improved_tail_width,
            )
            detail = apply_improved_tail_map(
                detail, np.asarray(stats["detail_std"], dtype=np.float64),
                base_scale=base_scale, tail_strength=tail_strength, tail_width=tail_width,
            )
            improved_initializer = {
                "base_scale": base_scale, "tail_strength": tail_strength, "tail_width": tail_width,
                "detail_scale": np.asarray(stats["detail_std"], dtype=np.float64).tolist(),
                "application": "sweep_zero_only_before_coordinate_MH",
            }
        current = build_state(coarse, detail, source_index, np.full(args.n_chains, -1, dtype=np.int64), kernel=kernel, action=action)
        initial_role = "direct_native_coarse_improved_wrapped_flow_initial" if args.initialization == "direct_coarse_impflow" else "direct_native_coarse_wrapped_flow_initial"

    initial_reb = float(np.max(reblock_error(current.phi, current.coarse, kernel)[0]))
    if initial_reb > REB_TOL:
        raise RuntimeError(f"initial reblocking failed: {initial_reb:.6g}")
    jacobian = detail_map_jacobian_check(kernel, lc)
    if jacobian.get("performed") and float(jacobian["linearity_max_abs_error"]) > 5.0e-6:
        raise RuntimeError("detail-coordinate map failed linearity check")
    write_json(run / "debug" / "detail_coordinate_jacobian_validation.json", jacobian)

    config = vars(args) | {
        "lambda": 1.0, "kappa_c": 0.340301, "kappa_f": 0.340301,
        "L_c": lc, "L_f": lf, "kernel_metadata": kernel_meta,
        "flow_load_report": load_report,
        "resume": resume_info,
        "initializer": (
            "improved_wrapped_flow_only_at_sweep_zero" if args.initialization == "direct_coarse_impflow"
            else "native_blocked_coarse_wrapped_flow_detail_only_at_sweep_zero" if args.initialization == "blocked_native_flow"
            else "wrapped_flow_only_at_sweep_zero"
        ),
        "improved_initializer": improved_initializer,
        "coarse_proposal": "per-site Metropolis kernel targeting exp(-S_c)" if args.coarse_proposal_mode == "sc_reversible" else "symmetric Gaussian checkerboard random walk in coarse coordinates",
        "detail_proposal": "symmetric Gaussian random walk in selected physical detail coordinates",
        "coarse_acceptance_formula": (
            "-S_f(new)+S_f(old)+S_c(new)-S_c(old)"
            if args.coarse_proposal_mode == "sc_reversible"
            else "-S_f(new)+S_f(old)"
        ),
        "detail_acceptance_formula": "-S_f(new)+S_f(old)",
        "jacobian_convention": "fixed inverse-block and interleaving Jacobians cancel between old and new coordinate states",
        "unique_coarse_configurations": n_unique_coarse,
        "detail_passes_per_sweep": args.detail_passes_per_sweep,
        "initial_detail_only_sweeps": args.initial_detail_only_sweeps,
        "details_per_coarse": args.details_per_coarse,
        "detail_replica_semantics": "Each repeated coarse field receives an independent wrapped-flow latent draw at sweep zero; coordinate-MH RNG remains chain-specific thereafter.",
        "sweep_semantics": "After optional initial detail-only sweeps, one full coarse-lattice update followed by detail_passes_per_sweep full-lattice detail-coordinate passes.",
    }
    write_json(run / "run_config.json", config)
    (run / "run_config.yaml").write_text(json.dumps(config, indent=2, default=str) + "\n", encoding="utf-8")
    (run / "submit_manifest.txt").write_text(
        "driver_command: " + " ".join(sys.argv) + "\n" + json.dumps(config, indent=2, default=str) + "\n",
        encoding="utf-8",
    )
    inventory = [{"role": initial_role, "chain_id": int(i), "source_index": int(current.source_index[i])} for i in range(args.n_chains)]
    inventory += [{"role": "native_reference", "chain_id": int(i), "source_index": int(index)} for i, index in enumerate(native_index)]
    write_csv(run / "source_index_inventory.csv", inventory, ["role", "chain_id", "source_index"])
    write_csv(
        run / "detail_replica_inventory.csv",
        [{"chain_id": int(i), "source_coarse_index": int(source_index[i]), "detail_replica_index": int(detail_replica_index[i])} for i in range(args.n_chains)],
        ["chain_id", "source_coarse_index", "detail_replica_index"],
    )

    yy, xx = np.indices((lc, lc))
    subsets = [(oy, ox, (yy % args.divide == oy) & (xx % args.divide == ox)) for oy in range(args.divide) for ox in range(args.divide)]
    prethermal_rows: list[dict[str, Any]] = []
    pre_action_start = float(np.mean(current.action) / (lf * lf))
    for pre_sweep in range(1, args.initial_detail_only_sweeps + 1):
        attempts = 0
        accepts = 0
        for detail_pass in range(1, args.detail_passes_per_sweep + 1):
            for oy, ox, active in subsets:
                for name, sector in (("d01", 0), ("d10", 1), ("d11", 2)):
                    detail_new = current.detail.copy()
                    noise = rng.standard_normal(detail_new[:, sector].shape).astype(np.float32)
                    detail_new[:, sector, active] += args.detail_sigma * noise[:, active]
                    proposed = build_state(current.coarse, detail_new, current.source_index, current.source_native_index, kernel=kernel, action=action)
                    loga = -proposed.action + current.action
                    accepted = np.log(rng.random(args.n_chains)) < np.minimum(0.0, loga)
                    reb, _ = reblock_error(proposed.phi, proposed.coarse, kernel)
                    if float(np.max(reb)) > REB_TOL:
                        raise RuntimeError(f"initial detail-only {name} proposal reblocking failure: {float(np.max(reb)):.6g}")
                    accepts += int(accepted.sum())
                    attempts += args.n_chains
                    current = choose_state(current, proposed, accepted)
        prethermal_rows.append({
            "initial_detail_only_sweep": pre_sweep,
            "detail_acceptance": accepts / attempts,
            "detail_attempts": attempts,
            "detail_accepts": accepts,
            "action_density_mean": float(np.mean(current.action) / (lf * lf)),
        })
    write_csv(run / "observables" / "initial_detail_only_history.csv", prethermal_rows)
    write_json(run / "summaries" / "initial_detail_only_summary.json", {
        "requested_sweeps": args.initial_detail_only_sweeps,
        "detail_passes_per_sweep": args.detail_passes_per_sweep,
        "action_density_before": pre_action_start,
        "action_density_after": float(np.mean(current.action) / (lf * lf)),
        "numbered_initial_sweep": args.sweep_offset,
        "numbered_initial_sweep_is_after_initial_detail_only": True,
    })

    main_rows, g_rows = measurement_rows(current, args.sweep_offset)
    acceptance_rows: list[dict[str, Any]] = []
    coordinate_rows: list[dict[str, Any]] = []
    substep_rows: list[dict[str, Any]] = []
    total_accepts = {"coarse": 0, "d01": 0, "d10": 0, "d11": 0}
    total_attempts = {key: 0 for key in total_accepts}
    write_json(run / "status.json", {"status": "running", "current_sweep": args.sweep_offset, "run_dir": str(run)})
    save_checkpoint(run / "checkpoints" / f"checkpoint_sweep_{args.sweep_offset:04d}.npz", current)
    save_checkpoint(run / "checkpoints" / "checkpoint_latest.npz", current)
    write_measurements(run, main_rows, g_rows)
    write_csv(run / "observables" / "acceptance_history.csv", acceptance_rows, ACCEPT_COLUMNS)
    started = time.perf_counter()

    for sweep in range(args.sweep_offset + 1, args.sweep_offset + args.n_sweeps + 1):
        sweep_accepts = {key: 0 for key in total_accepts}
        sweep_attempts = {key: 0 for key in total_accepts}
        phases: list[tuple[int, list[tuple[str, int | None, float]]]] = []
        if args.update_mode == "coarse_detail":
            phases.append((0, [("coarse", None, args.coarse_sigma)]))
        for detail_pass in range(1, args.detail_passes_per_sweep + 1):
            phases.append((detail_pass, [("d01", 0, args.detail_sigma), ("d10", 1, args.detail_sigma), ("d11", 2, args.detail_sigma)]))
        for detail_pass, names in phases:
            for oy, ox, active in subsets:
                for name, sector, sigma in names:
                    old_sc = action_total(current.coarse, action).astype(np.float64)
                    coarse_kernel_accepts = np.zeros(args.n_chains, dtype=np.int64)
                    coarse_new = current.coarse.copy()
                    detail_new = current.detail.copy()
                    if sector is None:
                        if args.coarse_proposal_mode == "sc_reversible":
                            coarse_new, coarse_kernel_accepts = coarse_kernel_transition(
                                coarse_new, active, action=action, sigma=sigma,
                                n_steps=args.coarse_updates_per_sweep, rng=rng,
                            )
                        else:
                            # Same blockwise symmetric Gaussian random walk as a
                            # detail coordinate.  The proposal ratio is one, so
                            # accept directly with the fine action alone.
                            noise = rng.standard_normal(coarse_new.shape).astype(np.float32)
                            coarse_new[:, active] += sigma * noise[:, active]
                    else:
                        noise = rng.standard_normal(detail_new[:, sector].shape).astype(np.float32)
                        detail_new[:, sector, active] += sigma * noise[:, active]
                    proposed = build_state(coarse_new, detail_new, current.source_index, current.source_native_index, kernel=kernel, action=action)
                    new_sc = action_total(proposed.coarse, action).astype(np.float64)
                    # The coarse proposal kernel is reversible with exp(-S_c):
                    # log Q(reverse)/Q(forward) = S_c(new)-S_c(old).  Detail
                    # proposals are symmetric, so that term is absent for them.
                    loga = -proposed.action + current.action
                    if sector is None and args.coarse_proposal_mode == "sc_reversible":
                        loga += new_sc - old_sc
                    logu = np.log(rng.random(args.n_chains))
                    accepted = logu < np.minimum(0.0, loga)
                    reb, _ = reblock_error(proposed.phi, proposed.coarse, kernel)
                    if float(np.max(reb)) > REB_TOL:
                        raise RuntimeError(f"{name} proposal reblocking failure: {float(np.max(reb)):.6g}")
                    for chain in range(args.n_chains):
                        coordinate_rows.append({
                            "sweep": sweep, "detail_pass": detail_pass, "chain_id": chain, "coordinate": name,
                            "subset_y": oy, "subset_x": ox, "active_sites": int(active.sum()),
                            "attempted": 1, "accepted": int(accepted[chain]),
                            "old_S_f": float(current.action[chain]), "new_S_f": float(proposed.action[chain]),
                            "delta_S_f": float(proposed.action[chain] - current.action[chain]),
                            "old_S_c": float(old_sc[chain]), "new_S_c": float(new_sc[chain]),
                            "coarse_kernel_site_accepts": int(coarse_kernel_accepts[chain]),
                            "log_accept_ratio": float(loga[chain]), "log_uniform": float(logu[chain]),
                            "reblocking_max_error": float(reb[chain]),
                        })
                    accepts = int(accepted.sum())
                    total_accepts[name] += accepts
                    total_attempts[name] += args.n_chains
                    sweep_accepts[name] += accepts
                    sweep_attempts[name] += args.n_chains
                    substep_rows.append({
                        "sweep": sweep, "detail_pass": detail_pass, "coordinate": name, "subset_y": oy, "subset_x": ox,
                        "attempts": args.n_chains, "accepts": accepts, "acceptance": accepts / args.n_chains,
                        "attempts_cumulative": total_attempts[name], "accepts_cumulative": total_accepts[name],
                        "acceptance_cumulative": total_accepts[name] / total_attempts[name],
                    })
                    current = choose_state(current, proposed, accepted)

        detail_attempts = sum(sweep_attempts[key] for key in ("d01", "d10", "d11"))
        detail_accepts = sum(sweep_accepts[key] for key in ("d01", "d10", "d11"))
        cumulative_detail_attempts = sum(total_attempts[key] for key in ("d01", "d10", "d11"))
        cumulative_detail_accepts = sum(total_accepts[key] for key in ("d01", "d10", "d11"))
        acceptance_rows.append({
            "sweep": sweep, "update_mode": f"coordinate_{args.update_mode}_divide{args.divide}",
            "coarse_acceptance": sweep_accepts["coarse"] / sweep_attempts["coarse"] if sweep_attempts["coarse"] else float("nan"),
            "coarse_proposals": sweep_attempts["coarse"], "coarse_accepts": sweep_accepts["coarse"],
            "coarse_acceptance_cumulative": total_accepts["coarse"] / total_attempts["coarse"] if total_attempts["coarse"] else float("nan"),
            "coarse_proposals_cumulative": total_attempts["coarse"], "coarse_accepts_cumulative": total_accepts["coarse"],
            "detail_acceptance": detail_accepts / detail_attempts,
            "detail_proposals": detail_attempts, "detail_accepts": detail_accepts,
            "detail_acceptance_cumulative": cumulative_detail_accepts / cumulative_detail_attempts,
            "detail_proposals_cumulative": cumulative_detail_attempts,
            "detail_accepts_cumulative": cumulative_detail_accepts,
            "conditional_flow_refreshes": 0,
        })
        if sweep in saves:
            rows, grows = measurement_rows(current, sweep)
            main_rows.extend(rows)
            g_rows.extend(grows)
            write_measurements(run, main_rows, g_rows)
            save_checkpoint(run / "checkpoints" / f"checkpoint_sweep_{sweep:04d}.npz", current)
        save_checkpoint(run / "checkpoints" / "checkpoint_latest.npz", current)
        # These files can contain millions of rows.  Append this sweep's rows
        # and release them instead of rewriting the complete history O(S^2).
        append_csv(run / "debug" / "coordinate_mh_diagnostics.csv", coordinate_rows, COORD_COLUMNS)
        append_csv(run / "debug" / "coordinate_substep_acceptance.csv", substep_rows, SUBSTEP_COLUMNS)
        coordinate_rows.clear()
        substep_rows.clear()
        write_csv(run / "observables" / "acceptance_history.csv", acceptance_rows, ACCEPT_COLUMNS)
        write_json(run / "status.json", {
            "status": "running", "current_sweep": sweep,
            "coordinate_acceptance": {key: total_accepts[key] / total_attempts[key] if total_attempts[key] else float("nan") for key in total_attempts},
            "run_dir": str(run),
        })
        print(json.dumps({
            "sweep": sweep, "accept_detail": detail_accepts / detail_attempts,
            "accept_by_coordinate": {key: sweep_accepts[key] / sweep_attempts[key] if sweep_attempts[key] else None for key in sweep_attempts},
            "measured": sweep in saves,
        }), flush=True)

    native_reference = build_state(native_c, native_d, np.full(args.n_chains, -1, dtype=np.int64), native_index, kernel=kernel, action=action)
    native_rows, _ = measurement_rows(native_reference, 0)
    write_csv(run / "observables" / f"native_L{lf}_reference_summary.csv", aggregate(native_rows))
    comparisons: list[dict[str, Any]] = []
    keys = ("action_density", "phi2", "phi4", "NN", "diag", "2nn", "m2", "m4")
    for sweep in sorted({int(row["sweep"]) for row in main_rows}):
        rows = [row for row in main_rows if int(row["sweep"]) == sweep]
        for key in keys:
            x = np.asarray([float(row[key]) for row in rows], dtype=np.float64)
            y = np.asarray([float(row[key]) for row in native_rows], dtype=np.float64)
            comparisons.append({"sweep": sweep, "observable": key, "mean": float(x.mean()), "native_mean": float(y.mean()), "mean_shift_native_sigma": float((x.mean() - y.mean()) / max(y.std(ddof=1), 1.0e-300)), "std_ratio": float(x.std(ddof=1) / max(y.std(ddof=1), 1.0e-300)) if len(x) > 1 else float("nan")})
    write_csv(run / "observables" / "sweep_native_comparison.csv", comparisons)
    final_reb = float(np.max(reblock_error(current.phi, current.coarse, kernel)[0]))
    summary = {
        "status": "completed", "update_mode": args.update_mode,
        "coordinate_acceptance": {key: total_accepts[key] / total_attempts[key] if total_attempts[key] else float("nan") for key in total_attempts},
        "final_reblocking_max": final_reb, "runtime_sec": time.perf_counter() - started,
        "detail_jacobian_validation": jacobian,
        "acceptance_ratio": {
            "detail": "-S_f(new)+S_f(old)",
            "coarse": "-S_f(new)+S_f(old)+S_c(new)-S_c(old)" if args.coarse_proposal_mode == "sc_reversible" else "-S_f(new)+S_f(old)",
        },
        "flow_used_after_sweep_zero": False,
    }
    write_json(run / "summaries" / "run_summary.json", summary)
    (run / "summaries" / "coordinate_mh_derivation.md").write_text(
        "# Coordinate-MH acceptance\n\n"
        "The Markov state is `(c,d01,d10,d11)`. Detail subsets receive additive independent Gaussian proposals, so their proposal ratio is one and `logA_detail=-S_f(new)+S_f(old)`. For coarse mode `sc_reversible`, a per-site kernel reversible with `exp(-S_c)` gives `logA_coarse=-S_f(new)+S_f(old)+S_c(new)-S_c(old)`. For coarse mode `symmetric_rw`, the coarse checkerboard subset receives the same additive Gaussian proposal as a detail coordinate and `logA_coarse=-S_f(new)+S_f(old)`. `psi=interleave(c,d01,d10,d11)` is a permutation and `phi=K^{-1} psi` is fixed linear. Their volume factor is independent of state and cancels in every ratio. The wrapped flow constructs sweep zero only and is absent from all later acceptance ratios.\n",
        encoding="utf-8",
    )
    write_json(run / "status.json", {"status": "completed", "current_sweep": args.sweep_offset + args.n_sweeps, "latest_checkpoint": str(run / "checkpoints" / "checkpoint_latest.npz"), **summary})
    print(json.dumps({"run_dir": str(run), **summary}, indent=2), flush=True)
    return 0


def write_failure_status(exc: Exception) -> None:
    try:
        run = Path(sys.argv[sys.argv.index("--run-dir") + 1]).resolve()
        if run.exists():
            write_json(run / "status.json", {"status": "failed", "run_dir": str(run), "exception_type": type(exc).__name__, "exception": str(exc), "traceback": traceback.format_exc()})
    except Exception:
        pass


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except SystemExit:
        raise
    except Exception as exc:
        write_failure_status(exc)
        raise
